source 'https://github.com/CocoaPods/Specs.git'

target 'AGLocationDispatcher', :exclusive => true do
  pod "AGLocationDispatcher", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "AGLocationDispatcher", :path => "../"

  
end
